listener 8883
allow_anonymous false
cafile /private/ca.crt
certfile /private/server.crt
keyfile /private/server.key
plugin /usr/lib/mosquitto_dynamic_security.so
plugin_opt_config_file /private/dynamic-security.json
max_packet_size 20000
max_inflight_messages 10
max_queued_messages 20
log_type error
log_type warning
log_type notice
