import {randomBytes,scryptSync,timingSafeEqual,createHmac,createSign,createVerify,createHash} from 'node:crypto';
export const random=()=>randomBytes(24).toString('base64url');
export const hash=s=>createHash('sha256').update(s).digest('hex');
export function passwordHash(p){if(typeof p!=='string'||p.length<12||p.length>128)throw Error('password-length');let salt=random();return `${salt}:${scryptSync(p,salt,32).toString('hex')}`;}
export function passwordValid(p,stored){if(typeof p!=='string'||p.length>128)return false;const [salt,h]=stored.split(':');return timingSafeEqual(scryptSync(p,salt,32),Buffer.from(h,'hex'));}
export function accessToken(sub,secret,now=Date.now()){let payload=Buffer.from(JSON.stringify({sub,exp:now+3600000})).toString('base64url');return payload+'.'+createHmac('sha256',secret).update(payload).digest('base64url');}
export function identity(token,secret,now=Date.now()){if(typeof token!=='string')throw Error('unauthorized');let [p,s,...rest]=token.split('.');let expected=createHmac('sha256',secret).update(p).digest('base64url');if(rest.length||!s||s.length!==expected.length||!timingSafeEqual(Buffer.from(s),Buffer.from(expected)))throw Error('unauthorized');let claims=JSON.parse(Buffer.from(p,'base64url'));if(claims.exp<=now)throw Error('unauthorized');return claims.sub;}
export function signGrant(claims,key){const header=Buffer.from('{"alg":"RS256","typ":"JWT"}').toString('base64url');const body=Buffer.from(JSON.stringify(claims)).toString('base64url');const data=header+'.'+body;return data+'.'+createSign('RSA-SHA256').update(data).sign(key).toString('base64url');}
export function verifyGrant(token,key){const [h,b,s]=token.split('.');if(JSON.parse(Buffer.from(h,'base64url')).alg!=='RS256'||!createVerify('RSA-SHA256').update(h+'.'+b).verify(key,Buffer.from(s,'base64url')))throw Error('signature');return JSON.parse(Buffer.from(b,'base64url'));}
